### ISSUE TITLE
There is a typo in the document

### ISSUE THREAD

**Issue by wolfogre** [newreleasesio/client-go#1]
![image](https://user-images.githubusercontent.com/9418365/82402828-f6cf4100-9a8f-11ea-85b4-a6d8a6c997c9.png)

See https://newreleases.io/api/v1

I can not find anywhere else to submit an issue for the website, so wrote it here.

**Comment by janos** [comment]
Hi, Jason. Thanks for reporting this problem. It has been fixed now.
