### ISSUE TITLE
The limit of the API has been changed?

### ISSUE THREAD

**Issue by wolfogre** [newreleasesio/client-go#2]
I found that the limit of the API has been changed from 1000 to 25000 today.

![image](https://user-images.githubusercontent.com/9418365/82403559-b53f9580-9a91-11ea-882d-a56ee66a9ec0.png)

Is that a bug or a new feature?

I could not find your email so I wrote it here. I am a developer from China, use golang at work, if there is anything I can help to do with newreleasesio, just call me via `echo aUB3b2xmb2dyZS5jb20K | base64 --decode`

**Comment by janos** [comment]
Hi, thank you for reporting this. I am glad that you noticed. This has indeed been changed a few hours ago, but only temporary for a specific needs of a user. API rate limit will be returned to 1000 soon.

If you have other questions, feel free to contact us over https://newreleases.io/contact. Thank you for your offer to help.
