### ISSUE TITLE
Does not report of new releases in case of the assets only update

### ISSUE THREAD

**Issue by andry81** [newreleasesio/client-go#7]
I have noted at least of one project that the website does not track properly:

https://newreleases.io/github/itlezy/eMule

It reports that the last update was 3 months ago:

```
3 months ago:
[eMule_v0.60d-broadband](https://newreleases.io/github/itlezy/eMule?version=eMule_v0.60d-broadband) pre
10 months ago:
eMule_v0.60d-community
a year ago:
eMule_v0.60c-community
2 years ago:
eMule_v0.60b-community
eMule_v0.60a-community
3 years ago:
eMule_v0.51d-community
4 years ago:
eMule_v0.51c-community
eMule_v0.51b-community
eMule_v0.51a-unofficial
5 years ago:
eMule_v0.50b-unofficial
```

While the actual state of the repo:

https://github.com/itlezy/eMule/releases

https://github.com/itlezy/eMule/releases/tag/eMule_v0.60d-broadband

The reason is in the content. You track only tags/releases creation, when it is not enough. Needs to track the assets update too.

**Comment by janos** [comment]
Yes, that is correct. NewReleases does not track updates on the assets, only on tag ref change (retagging) or release note update, currently. The reason for this is mainly as NewReleases does not provide information about assets, only text of the release not. It is not impossible that assets tracking will be added sometime in the future.
